controller_list:
  - name: fake_full_move_controller
    joints:
      - omni_base
      - rbkairos_ur10_shoulder_pan_joint
      - rbkairos_ur10_shoulder_lift_joint
      - rbkairos_ur10_elbow_joint
      - rbkairos_ur10_wrist_1_joint
      - rbkairos_ur10_wrist_2_joint
      - rbkairos_ur10_wrist_3_joint